export default [
  {
    name: "Murloc Raider",
    cost: 1,
    attack: 2,
    health: 1,
    description: "",
    target: ["card", "hero"],
    special: "",
    attackinc: "",
    defenseinc: "",
    type: "minion",
    turn: 1,
  },
  {
    name: "Bloodfen Raptor",
    cost: 2,
    attack: 3,
    health: 2,
    description: "",
    target: ["card", "hero"],
    special: "",
    attackinc: "",
    defenseinc: "",
    type: "minion",
    turn: 1,
  },
  {
    name: "River crocolisk",
    cost: 2,
    attack: 2,
    health: 3,
    description: "",
    target: ["card", "hero"],
    special: "",
    attackinc: "",
    defenseinc: "",
    type: "minion",
    turn: 1,
  },
  {
    name: "Fireball",
    cost: 4,
    attack: "",
    health: "",
    description: "deal 6 damage",
    target: ["card", "hero"],
    special: "",
    attackinc: "",
    defenseinc: "",
    type: "spell",
    turn: 1,
  },
  {
    name: "Raid Leader",
    cost: 3,
    attack: 2,
    health: 2,
    description: "Your other minions have +1 attacks",
    target: ["card", "hero"],
    special: "minion",
    attackinc: 1,
    defenseinc: "",
    type: "minion",
    turn: 1,
  },
  {
    name: "Magma Rager",
    cost: 3,
    attack: 5,
    health: 1,
    description: "",
    target: ["card", "hero"],
    special: "",
    attackinc: "",
    defenseinc: "",
    type: "minion",
    turn: 1,
  },
  {
    name: "Novice Engineer",
    cost: 2,
    attack: 1,
    health: 1,
    description: "Draw a card",
    target: ["card", "hero"],
    special: "draw",
    attackinc: "",
    defenseinc: "",
    type: "minion",
    turn: 1,
  },
  {
    name: "Nightblade",
    cost: 5,
    attack: 4,
    health: 4,
    description: "Battlecry: deal 3 damage to enemy hero",
    target: ["card", "hero"],
    special: "attack",
    attackinc: "",
    defenseinc: "",
    ability: {
      target: ["hero"],
      attack: 3,
    },
    type: "minion",
    turn: 1,
  },

  {
    name: "wolfrider",
    cost: 3,
    attack: 3,
    health: 1,
    description: "charge",
    target: ["card", "hero"],
    special: "",
    attackinc: "",
    defenseinc: "",
    type: "minion",
    turn: 0,
  },

  {
    name: "Sheildmasta",
    cost: 4,
    attack: 3,
    health: 5,
    description: "Taunt",
    target: ["card", "hero"],
    special: "defense",
    attackinc: "",
    defenseinc: "",
    ability: {
      target: ["hero", "card"],
      defense: 5,
    },
    type: "minion",
    turn: 1,
  },
];
